import { expect, test } from '@playwright/test';
import { mockCloud } from './cloud-fixture';
import { readBrowserRecords } from './record-fixture';

test('onboarding collects body inputs, reviews editable targets, and preserves them through reload and profile edits', async ({ page }) => {
  await mockCloud(page);
  await page.goto('/');
  await page.getByRole('button', {name:'Create account',exact:true}).click();
  await page.getByRole('button', {name:'Try on this device first'}).click();
  await page.getByLabel('Your name',{exact:true}).fill('Alex');
  await page.getByRole('button',{name:'That’s me. Let’s go.',exact:true}).click();
  await page.getByLabel('Your main goal',{exact:true}).selectOption('lose');
  await page.getByLabel('Weight unit',{exact:true}).selectOption('kg');
  await page.getByLabel('Current weight',{exact:true}).fill('80');
  await page.getByLabel('Target weight',{exact:true}).fill('75');
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('rep-and-plate.onboarding.draft.v1.guest')!).fitnessInput?.targetWeight)).toBe('75');
  await page.reload();
  await expect(page.getByLabel('Current weight',{exact:true})).toHaveValue('80');
  await expect(page.getByLabel('Target weight',{exact:true})).toHaveValue('75');
  await page.getByRole('button',{name:'Save my starting point',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Your daily targets.',exact:true})).toBeVisible();
  await page.getByLabel('Age (years)',{exact:true}).fill('30');
  await page.getByLabel('Height',{exact:true}).fill('180');
  await page.getByLabel('Usual activity',{exact:true}).selectOption('light');
  await page.getByLabel('Sex used for the estimate',{exact:true}).selectOption('male');
  await page.getByRole('button',{name:'Estimate my targets',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText('standard adult estimate');
  await expect(page.getByRole('checkbox',{name:'The standard adult estimate applies to me',exact:true})).toBeFocused();
  await page.getByRole('checkbox',{name:'The standard adult estimate applies to me',exact:true}).check();
  await page.screenshot({path:test.info().outputPath('personal-inputs.png'),fullPage:true});
  await page.getByRole('button',{name:'Estimate my targets',exact:true}).click();
  await expect(page.getByLabel('Daily calories',{exact:true})).toHaveValue('2600');
  await expect(page.getByLabel('Daily calories',{exact:true})).toBeFocused();
  expect(await readBrowserRecords(page)).toBeNull();
  await page.getByLabel('Daily calories',{exact:true}).fill('2500');
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('rep-and-plate.onboarding.draft.v1.guest')!).nutritionSession?.targets.calories)).toBe('2500');
  await page.reload();
  await expect(page.getByLabel('Daily calories',{exact:true})).toHaveValue('2500');
  expect(await readBrowserRecords(page)).toBeNull();
  await page.screenshot({path:test.info().outputPath('target-review.png'),fullPage:true});
  await page.getByRole('button',{name:'Use these daily targets',exact:true}).click();
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('rep-and-plate.onboarding.draft.v1.guest')!).step)).toBe('ready');
  await page.reload();
  await expect(page.getByText('2500 calories · 130g protein · 325g carbs · 87g fat. Change them anytime in your profile.',{exact:true})).toBeVisible();
  await page.screenshot({path:test.info().outputPath('targets-ready.png'),fullPage:true});
  await page.getByRole('button',{name:'Let’s do this',exact:true}).click();
  await expect(page.getByRole('button',{name:'Log my first meal',exact:true})).toBeVisible();
  expect(await page.evaluate(() => localStorage.getItem('rep-and-plate.onboarding.draft.v1.guest'))).toBeNull();
  await page.getByRole('button',{name:'Your profile',exact:true}).click();
  await page.getByRole('button',{name:'Calorie starting point',exact:true}).click();
  const dialog=page.getByRole('dialog',{name:'Your calorie starting point'});
  await expect(dialog.getByLabel('Age (years)',{exact:true})).toHaveValue('30');
  await expect(dialog.getByLabel('Height',{exact:true})).toHaveValue('180');
  await dialog.getByLabel('Age (years)',{exact:true}).fill('31');
  await dialog.getByRole('button',{name:'Save details without targets',exact:true}).click();
  await page.reload();
  await page.getByRole('button',{name:'Calorie starting point',exact:true}).click();
  await expect(dialog.getByLabel('Age (years)',{exact:true})).toHaveValue('31');
  const saved=await readBrowserRecords(page);
  expect(saved.profile.nutritionBaseline).toEqual({age:31,heightCm:180,sex:'male',activity:'light',calorieApproach:'lose'});
  expect(saved.profile).toMatchObject({calories:2500,protein:130,carbs:325,fat:87,targetsConfigured:true});
  expect(saved.bodyWeights).toHaveLength(1);
  expect(saved.meals).toHaveLength(0);
});

test('skipping weight setup still offers personal details and saves them without activating sample targets', async ({page}) => {
  await mockCloud(page);
  await page.goto('/');
  await page.getByRole('button',{name:'Create account',exact:true}).click();
  await page.getByRole('button',{name:'Try on this device first'}).click();
  await page.getByLabel('Your name',{exact:true}).fill('Taylor');
  await page.getByRole('button',{name:'That’s me. Let’s go.',exact:true}).click();
  await page.getByRole('button',{name:'Set this up later',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Your daily targets.',exact:true})).toBeVisible();
  await page.getByLabel('Age (years)',{exact:true}).fill('28');
  await page.getByLabel('Height unit',{exact:true}).selectOption('in');
  await page.getByLabel('Height',{exact:true}).fill('65');
  await page.getByLabel('Usual activity',{exact:true}).selectOption('moderate');
  await page.getByText('Other ways to set targets',{exact:true}).click();
  await page.getByRole('button',{name:'Save details without targets',exact:true}).click();
  await page.getByRole('button',{name:'Let’s do this',exact:true}).click();
  const saved=await readBrowserRecords(page);
  expect(saved.profile.nutritionBaseline).toMatchObject({age:28,heightCm:165.1,sex:'none',activity:'moderate'});
  expect(saved.profile.targetsConfigured).toBe(false);
  expect(saved.bodyWeights??[]).toHaveLength(0);
});
