import {test,expect} from './app-fixture';
import {readBrowserRecords,seedBrowserRecords} from './record-fixture';

test.beforeEach(async({page})=>{await page.route('**/api/status',r=>r.fulfill({json:{available:false,jev:false}}));await page.goto('/#workouts');});
test('rest survives navigation, reload and elapsed wall time',async({page})=>{
 await page.clock.install();
 await page.getByRole('button',{name:'Start workout',exact:true}).click();
 await page.getByText('Rest timer',{exact:true}).click();
 await page.getByRole('button',{name:'Start 90-second rest',exact:true}).click();
 const end=(await readBrowserRecords(page)).workout.restUntil;
 expect(end).toBeGreaterThan(Date.now());
 await page.getByRole('button',{name:'Nutrition',exact:true}).click();
 await page.clock.fastForward(30000);
 await page.getByRole('button',{name:'Workouts',exact:true}).click();
 await page.getByText(/^\d+s rest$/).click();
 await expect(page.getByLabel('Rest remaining')).toContainText(/(?:5\d|60)s remaining/);
 expect((await readBrowserRecords(page)).workout.restUntil).toBe(end);
 await page.reload();await page.getByText(/^\d+s rest$/).click();
 expect((await readBrowserRecords(page)).workout.restUntil).toBe(end);
 await page.getByRole('button',{name:'End rest',exact:true}).click();
 await expect.poll(async()=>(await readBrowserRecords(page)).workout.restUntil).toBeNull();
});
test('all older sessions remain visible and can be reopened for correction',async({page})=>{
 await expect(page.getByRole('button',{name:'Start workout',exact:true})).toBeVisible();
 const state=await readBrowserRecords(page);
 state.workout.history=Array.from({length:13},(_,i)=>({title:`Recorded day ${i+1}`,startedAt:`2026-09-${String(i+1).padStart(2,'0')}T12:00:00Z`,finishedAt:`2026-09-${String(i+1).padStart(2,'0')}T13:00:00Z`,exercises:[{name:'Personal press',weight:100,target:8,sets:[8],previous:[]}]}));
 state.workout.history[12].exercises=Array.from({length:9},(_,i)=>({name:`Lift ${i+1}`,weight:100,target:8,sets:Array(12).fill(8),previous:[]}));
 await seedBrowserRecords(page,state);await page.reload();
 await expect(page.getByText('112 sets across your latest 5 finished sessions.',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Open workout menu',exact:true}).click();
 await page.getByRole('button',{name:'Session history',exact:true}).click();
 await expect(page.getByRole('dialog')).toContainText('Your 13 finished sessions.');
 await page.getByRole('button',{name:'Correct Recorded day 1',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Recorded day 1 in progress',exact:true})).toBeVisible();
 expect((await readBrowserRecords(page)).workout.exercises[0].sets).toEqual([8]);
});
test('chosen units, remaining-set loads and personal routine survive return without recording old work',async({page},info)=>{
 await page.getByLabel('Workout units').selectOption('kg');
 await page.getByRole('button',{name:'Start workout',exact:true}).click();
 const bench=page.getByRole('region',{name:'Bench Press',exact:true});
 await page.getByLabel('Bench Press set 1 weight (kg)',{exact:true}).fill('80');
 await bench.locator('.workout-set').first().getByRole('button',{name:'Save set weight',exact:true}).click();
 await page.getByRole('button',{name:'Use this load for remaining Bench Press sets',exact:true}).click();
 await page.getByRole('button',{name:'Bench Press set 1: 8 reps',exact:true}).click();
 await expect(page.getByText('Got it. Bench Press, set 1: 80 kg × 8 reps.',{exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Bench Press set 2: 8 reps',exact:true})).toBeEnabled();
 await page.getByRole('button',{name:'Saved routines',exact:true}).click();
 await page.getByLabel('Routine name').fill('Personal upper');
 await page.getByRole('button',{name:'Save current lineup as routine',exact:true}).click();
 await expect(page.getByRole('button',{name:'Start routine Personal upper',exact:true})).toBeDisabled();
 await page.getByRole('button',{name:'Close dialog',exact:true}).click();
 await page.getByRole('button',{name:'Finish workout',exact:true}).click();await page.getByRole('button',{name:'Save partial workout',exact:true}).click();
 await page.reload();await page.getByRole('button',{name:'Saved routines',exact:true}).click();
 await expect(page.getByRole('dialog')).toContainText('Previous reference 80 kg');
 await page.screenshot({path:info.outputPath('review-routine.png')});
 await page.getByRole('button',{name:'Start routine Personal upper',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Personal upper in progress',exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Bench Press set 1: 8 reps',exact:true})).toBeDisabled();
 const saved=await readBrowserRecords(page);
 expect(saved.workout.exercises[0].sets).toEqual([null,null,null]);
 expect(saved.workout.history.at(-1).exercises[0].sets).toEqual([8,null,null]);
 expect(saved.workout.routines).toHaveLength(1);
 await page.getByRole('button',{name:'Saved routines',exact:true}).click();await page.getByRole('button',{name:'Remove routine Personal upper',exact:true}).click();await page.getByRole('button',{name:'Confirm remove routine',exact:true}).click();
 await expect.poll(async()=>(await readBrowserRecords(page)).workout.routines.length).toBe(0);
 expect((await readBrowserRecords(page)).workout.history).toHaveLength(1);
});
test('confirming the existing zero reference updates all remaining load fields',async({page})=>{
 await page.getByRole('button',{name:'Start workout',exact:true}).click();
 const bench=page.getByRole('region',{name:'Bench Press',exact:true});
 await page.getByLabel('Bench Press set 1 weight (lb)',{exact:true}).fill('0');
 await bench.locator('.workout-set').first().getByRole('button',{name:'Save set weight',exact:true}).click();
 await page.getByRole('button',{name:'Use this load for remaining Bench Press sets',exact:true}).click();
 await expect(page.getByLabel('Bench Press set 2 weight (lb)',{exact:true})).toHaveValue('0');
 expect((await readBrowserRecords(page)).workout.exercises[0].sets).toEqual([null,null,null]);
});
