import { expect, test } from '@playwright/test';
import { mockCloud } from '../../tests/cloud-fixture';

test('native onboarding collects personal inputs, reviews calorie targets and restores them in the profile', async ({page}) => {
  await mockCloud(page);
  await page.addInitScript(() => sessionStorage.setItem('health.connection', JSON.stringify({url:'https://health-beta.example',token:''})));
  await page.goto('/');
  await page.getByRole('button',{name:'Create account',exact:true}).click();
  await page.getByRole('button',{name:'Try on this device first'}).click();
  await page.getByRole('textbox',{name:'Your name',exact:true}).fill('Alex');
  await page.getByRole('button',{name:'That’s me. Let’s go.',exact:true}).click();
  await page.getByRole('button',{name:'Lose weight',exact:true}).click();
  await page.getByRole('button',{name:'kg',exact:true}).click();
  await page.getByRole('textbox',{name:'Current weight',exact:true}).fill('80');
  await page.getByRole('textbox',{name:'Target weight',exact:true}).fill('75');
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('rep-and-plate.onboarding.draft.v1.guest')!).fitnessInput?.targetWeight)).toBe('75');
  await page.reload();
  await expect(page.getByRole('textbox',{name:'Current weight',exact:true})).toHaveValue('80');
  await page.getByRole('button',{name:'Save my starting point',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Your daily targets.',exact:true})).toBeVisible();
  await page.getByRole('textbox',{name:'Age (years)',exact:true}).fill('30');
  await page.getByRole('textbox',{name:'Height',exact:true}).fill('180');
  await page.getByRole('button',{name:'Mostly sitting · some walking or exercise',exact:true}).click();
  await page.getByRole('button',{name:'Male',exact:true}).click();
  await page.getByRole('checkbox',{name:'The standard adult estimate applies to me',exact:true}).click();
  await page.getByRole('button',{name:'Estimate my targets',exact:true}).click();
  await expect(page.getByRole('textbox',{name:'Daily calories',exact:true})).toHaveValue('2600');
  await page.getByRole('textbox',{name:'Daily calories',exact:true}).fill('2500');
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('rep-and-plate.onboarding.draft.v1.guest')!).nutritionSession?.targets.calories)).toBe('2500');
  await page.reload();
  await expect(page.getByRole('textbox',{name:'Daily calories',exact:true})).toHaveValue('2500');
  await page.getByRole('button',{name:'Use these daily targets',exact:true}).click();
  await page.getByRole('button',{name:'Let’s do this',exact:true}).click();
  await expect(page.getByRole('button',{name:'Log my first meal',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Your profile',exact:true}).click();
  await page.getByRole('button',{name:'Calorie starting point',exact:true}).click();
  await expect(page.getByRole('textbox',{name:'Age (years)',exact:true})).toHaveValue('30');
  await page.getByRole('textbox',{name:'Age (years)',exact:true}).fill('31');
  await page.getByRole('button',{name:'Save details without targets',exact:true}).click();
  await page.reload();
  await page.getByRole('button',{name:'Your profile',exact:true}).click();
  await expect(page.getByRole('button',{name:'Calorie starting point',exact:true})).toBeVisible();
  const saved=await page.evaluate(() => JSON.parse(localStorage.getItem('dannys-health.native.v1')!));
  expect(saved.profile.nutritionBaseline).toEqual({age:31,heightCm:180,sex:'male',activity:'light',calorieApproach:'lose'});
  expect(saved.profile).toMatchObject({calories:2500,protein:130,carbs:325,fat:87,targetsConfigured:true});
  expect(saved.bodyWeights).toHaveLength(1);
  expect(saved.meals).toHaveLength(0);
});
