import { expect, test } from '@playwright/test';
import { mockCloud } from '../../tests/cloud-fixture';

test('native unfinished account setup resumes after reload and later sign-in', async ({page}) => {
  await mockCloud(page);
  await page.addInitScript(() => sessionStorage.setItem('health.connection', JSON.stringify({url:'https://health-beta.example',token:''})));
  await page.goto('/');
  await page.getByRole('button',{name:'Sign in',exact:true}).click();
  await page.getByRole('textbox',{name:'Email',exact:true}).fill('fixture@example.test');
  await page.getByRole('textbox',{name:'Password',exact:true}).fill('test-password-only');
  await page.getByRole('button',{name:'Sign in',exact:true}).last().click();
  await page.getByRole('textbox',{name:'Your name',exact:true}).fill('Alex');
  await page.getByRole('checkbox',{name:'These device records are mine',exact:true}).click();
  await page.getByRole('button',{name:'That’s me. Let’s go.',exact:true}).click();
  await page.getByRole('textbox',{name:'Current weight',exact:true}).fill('180');
  const key='rep-and-plate.onboarding.draft.v1.account:11111111-1111-4111-8111-111111111111';
  await expect.poll(() => page.evaluate(key => JSON.parse(localStorage.getItem(key)!).fitnessInput?.currentWeight,key)).toBe('180');
  const raw=await page.evaluate(key => localStorage.getItem(key)!,key);
  expect(raw).not.toContain('test-password-only');
  expect(raw).not.toContain('fixture@example.test');
  await page.reload();
  await expect(page.getByRole('textbox',{name:'Current weight',exact:true})).toHaveValue('180');
  await page.getByRole('button',{name:'Sign out',exact:true}).click();
  await page.getByRole('button',{name:'Sign in',exact:true}).click();
  await page.getByRole('textbox',{name:'Email',exact:true}).fill('fixture@example.test');
  await page.getByRole('textbox',{name:'Password',exact:true}).fill('test-password-only');
  await page.getByRole('button',{name:'Sign in',exact:true}).last().click();
  await expect(page.getByRole('textbox',{name:'Current weight',exact:true})).toHaveValue('180');
  const records=await page.evaluate(() => JSON.parse(localStorage.getItem('dannys-health.native.v1') ?? 'null'));
  expect(records?.bodyWeights ?? []).toHaveLength(0);
});
